name: Johnna Berryhill
description: Graduate Student
menu:
 - page: About
   url: /about
 - page: Papers
   url: /papers
   links:
    - title: Working papers
      url: "#working-papers"
    - title: Published papers
      url: "#published-papers"
 - page: Research Projects
   url: /research
   links:
    - title: "Masters Thesis"
      url: "#Masters Thesis"
    - title: "Undergraduate Thesis"
      url: "#Undergraduate Thesis"
    - title: "NCTR Internship Project"
      url: "#NCTR Internship Project"
    - title: "Consulting Project"
      url: "#Consulting Project"
 - page: Curriculum Vitae
   url: assets/images/jb_CV_May2024.pdf  # Change this to point directly to the PDF
 - page: Education
   url: /education
 - page: Presentations
   url: /Presentations
menu_external:
 - title: LinkedIn
   url: "https://www.linkedin.com/in/johnna-berryhill/"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: johnnaberryhill.github.io
locale: en_GB
